export { default as Alarm } from './icons-alarm'
export { default as Home } from './icons-home'
export { default as MoneySack } from './icons-money'
export { default as Memo } from './icons-memo'
export { default as Statistic } from './icons-statistic'
export { default as Users } from './icons-users'
